# 1. BASE DE DATOS MYSQL (VOLUMEN PERSISTENTE Y SERVICIO)
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mysql-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: db-mysql
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mysql
  template:
    metadata:
      labels:
        app: mysql
    spec:
      containers:
        - name: mysql-container
          image: mysql:8.0
          env:
            - name: MYSQL_DATABASE
              value: "db_innovatech"
            - name: MYSQL_ROOT_PASSWORD
              value: "rootpassword"
          ports:
            - containerPort: 3306
          resources:
            requests:
              cpu: "100m"
              memory: "256Mi"
            limits:
              cpu: "250m"
              memory: "512Mi"
          volumeMounts:
            - name: mysql-data
              mountPath: /var/lib/mysql
      volumes:
        - name: mysql-data
          persistentVolumeClaim:
            claimName: mysql-pvc
---
apiVersion: v1
kind: Service
metadata:
  name: db-mysql
spec:
  selector:
    app: mysql
  ports:
    - port: 3306
      targetPort: 3306

---
# 2. BACKEND DESPACHOS
apiVersion: apps/v1
kind: Deployment
metadata:
  name: innovatech-back-despachos
spec:
  replicas: 1
  selector:
    matchLabels:
      app: back-despachos
  template:
    metadata:
      labels:
        app: back-despachos
    spec:
      containers:
        - name: backend-container
          image: 941678413307.dkr.ecr.us-east-1.amazonaws.com/microservice-despachos:latest
          ports:
            - containerPort: 8080
          env:
            - name: DB_ENDPOINT
              value: "db-mysql"
            - name: DB_PORT
              value: "3306"
            - name: DB_NAME
              value: "db_innovatech"
            - name: DB_USERNAME
              value: "root"
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: db-secrets
                  key: password
            - name: SPRING_DATASOURCE_URL
              value: "jdbc:mysql://db-mysql:3306/db_innovatech?allowPublicKeyRetrieval=true&useSSL=false&serverTimezone=UTC"
---
apiVersion: v1
kind: Service
metadata:
  name: innovatech-service-back
spec:
  type: ClusterIP
  selector:
    app: back-despachos
  ports:
    - port: 8080
      targetPort: 8080

---
# 3. BACKEND VENTAS
apiVersion: apps/v1
kind: Deployment
metadata:
  name: innovatech-back-ventas
spec:
  replicas: 1
  selector:
    matchLabels:
      app: back-ventas
  template:
    metadata:
      labels:
        app: back-ventas
    spec:
      containers:
        - name: ventas-container
          image: 941678413307.dkr.ecr.us-east-1.amazonaws.com/microservice-ventas:latest
          ports:
            - containerPort: 8081
          env:
            - name: DB_ENDPOINT
              value: "db-mysql"
            - name: DB_PORT
              value: "3306"
            - name: DB_NAME
              value: "db_innovatech"
            - name: DB_USERNAME
              value: "root"
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: db-secrets
                  key: password
            - name: SPRING_DATASOURCE_URL
              value: "jdbc:mysql://db-mysql:3306/db_innovatech?allowPublicKeyRetrieval=true&useSSL=false&serverTimezone=UTC"
---
apiVersion: v1
kind: Service
metadata:
  name: innovatech-service-ventas
spec:
  type: ClusterIP
  selector:
    app: back-ventas
  ports:
    - port: 8081
      targetPort: 8081

---
# 4. FRONTEND
apiVersion: apps/v1
kind: Deployment
metadata:
  name: innovatech-frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
        - name: frontend-container
          image: 941678413307.dkr.ecr.us-east-1.amazonaws.com/frontend:latest
          ports:
            - containerPort: 80
---
# ... existing aode ...